server:
  port: 9045

spring:
  application:
    name: comment-server

  # spring Data
  data:
    mongodb:
      host: 121.36.47.240
      database: burukeyou-comment

  # 注册中心
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

custom:
  ouath2:
    client:
      signingKey: 909090
      resourceId: ${spring.application.name}
      ignoreUrls:
        - /**

