spring:
  application:
    name: article-center-server

  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/burukeyou-user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    ##url: jdbc:mysql://cdb-dceafysi.cd.tencentcdb.com:10058/sc_admin?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # cloud
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    # 开启负载均衡器的失败重试功能
    loadbalancer:
      retry:
        enabled: true

  # 消息队列
  rabbitmq:
    host: 192.168.1.9
    port: 5672
    virtual-host: /burukeyou
    username: admin
    password: 123456

    listener:
      simple:
        concurrency: 5 # 并发消费者的初始化值
        max-concurrency: 10  # 并发消费者的最大值
        prefetch: 5 # 每个消费者每次监听时可拉取处理的消息数量。


server:
  port: 9035

# =======================================Mybatis-plus=======================================================
mybatis-plus:
  mapper-locations: classpath:/mybatis/mapper/*.xml


# =======================================Custom=========================================================
custom:
  ouath2:
    client:
      ignore-urls:
        - /user/login
        - /article/**
        - /**
      resource-id: ${spring.application.name}
      signing-key: 909090

  swagger2:
    basePackage: burukeyou.article.controller












