spring:
  application:
    name: file-center-server



server:
  port: 9060




custom:
  file:
    type: aliyun_oss
    oss:
      END_POINT: 
      ACCESS_KEY_ID: 
      ACCESS_KEY_SECRET: 
      BUCKET_NAME: burukeyou
