spring:
  application:
    name: im-server



server:
  port: 9052

# ================================================================================================


custom:
  im:
    port: 8088












