server:
  port: 8090
  servlet:
    context-path:

spring:
  application:
    name: zuul-gateway-server

  datasource:
    url: jdbc:mysql://localhost:3306/test02?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    show-sql: true

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848




# ===================================配置zuul网关============================================================
zuul:
  host:
    connect-timeout-millis: 120000
    socket-timeout-millis: 120000

  prefix: /api/v1
  routes:
    token:
      url: authentication-center-server
    search:
      url: search-center-server
    admin:
      url: admin-server
    user:
      url: user-server
    system:
      url: system-center-server
    article:
      url: article-center-server
    focus:
      url: focus-center-server
    boiling:
      url: boilling-center-server
    comment:
      url: comment-center-server

  #  默认敏感请求头比如Authorthtion是不会下发的，这里设置为空，就是所有请求头都向下转发
  sensitive-headers:


#=========================
ribbon:
  ReadTimeout: 120000  # 单位毫秒数
  SocketTimeout: 120000


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 120000


# ===================================配置鉴权客户端============================================================
custom:
  ouath2:
    client:
      signing-key: 909090
      resource-id: ${spring.application.name}
      ignore-urls:
        - /token/**
        - /**



