spring:
  # 消息队列
  rabbitmq:
    host: 192.168.1.19
    port: 5672
    virtual-host: /burukeyou
    username: guest
    password: guest

    listener:
      simple:
        concurrency: 5 # 并发消费者的初始化值
        max-concurrency: 10  # 并发消费者的最大值
        prefetch: 5 # 每个消费者每次监听时可拉取处理的消息数量。












