spring:
  application:
    name: im-server

  # cloud
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    # 开启负载均衡器的失败重试功能
    loadbalancer:
      retry:
        enabled: true


server:
  port: 9052

# ================================================================================================















