spring:
  application:
    name: im-server



server:
  port: 9053
  #port: 9055

# ================================================================================================


custom:
  im:
    port: 8081



nacos:
  discovery:
    server-addr: 127.0.0.1:8848








