spring:
  application:
    name: im-server



server:
  port: 9052

# ================================================================================================


custom:
  im:
    port: 8088



nacos:
  discovery:
    server-addr: 127.0.0.1:8848








