spring:
  application:
    name: notification-center-server

  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/burukeyou-user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    ##url: jdbc:mysql://cdb-dceafysi.cd.tencentcdb.com:10058/sc_admin?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # cloud
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    # 开启负载均衡器的失败重试功能
    loadbalancer:
      retry:
        enabled: true



  # 消息队列
  rabbitmq:
    host: 192.168.1.19
    port: 5672
    virtual-host: /burukeyou
    username: guest
    password: guest

    listener:
      simple:
        concurrency: 1 # 并发消费者的初始化值
        max-concurrency: 5  # 并发消费者的最大值
        prefetch: 1 # 每个消费者每次监听时可拉取处理的消息数量。
        acknowledge-mode: manual


server:
  port: 9065

# =======================================Custom=========================================================
custom:
  ouath2:
    client:
      ignore-urls:
        - /**
      resource-id: ${spring.application.name}
      signing-key: 909090

  swagger2:
    basePackage: burukeyou.notification.controller













