spring:
  application:
    name: authentication-center-server
  datasource:
    url: jdbc:mysql://localhost:3306/burukeyou-auth?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

server:
  port: 9020

feign:
  hystrix:
    enabled: true  # 启动hystrix熔断机制

mybatis-plus:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    #打印sql语句
